### ISSUE TITLE
Change the reasoning behind the exclusion of Search from the TDM capsule

### ISSUE THREAD

**Issue by llemeurfr** [lrosenthol/opt-out-vocab#13]
The current text contains: 
"Search and Discovery is a category that is separate from the others, as it is not a form of TDM or AI Training."
The statement that Search is not a form of TDM will be opaque to many.  

May I propose a slight evolution of this sentence, using part of the CDSM definition of TDM?

"Search and Discovery is kept separate from the TDM category because the goal of such service is not generating information or training a model, but  retrieving assets."

Even if the exact boundaries of the TDM concept cannot be framed easily, my take is that this sentence is not contentious when we use the term "goal" (or "purpose").

**Comment by paul2keller** [comment]
same here I think we have addressed this question in the latest version, which now states: 

> For the purposes of this vocabulary, TDM is not understood to cover indexing of content for the purpose of online search. This use case is addressed using a location- based schema such as the exiting Robots Exclusion Protocol.

Can you let us know if this is indeed the case @llemeurfr?

**Comment by llemeurfr** [comment]
I'm fine with the new wording. Closing this issue.
