### ISSUE TITLE
Aligning the definition of TDM with EU language and how to treat competing definitions?

### ISSUE THREAD

**Issue by paul2keller** [lrosenthol/opt-out-vocab#2]
Regarding TDM: I agree with Laurent that we should stay as close as possible to the wording of the directive here. However, I think we should be aware that what we are proposing here is a vocabulary that works outside the EU context, so I think we would need to add that this is the "European Union's Copyright in the Digital Single Market (CDSM) Directive".

I would also assume that we would need to justify our decision to use this definition (especially since there may be definitions of the term in other jurisdictions, although I am not sure, so that would require some research. As far as I know, the UK does - should be aligned - and Australia has something in draft).

**Comment by lrosenthol** [comment]
I also agree - however, there may be multiple definitions even in the EU.

The current document uses the text from Article 2.2 of the CDSM
>"any automated analytical technique aiming to analyse text and data in digital form to generate information such as patterns, trends and correlations"

That is not exactly what Laurent wrote, which is:
>”‘text and data mining’ means any automated analytical technique aimed at analysing text and data in digital form in order to generate information which includes but is not limited to patterns, trends and correlations”.

I am happy to switch, provided I can get a specific citation for where that comes from in the CDSM.

**Comment by paul2keller** [comment]
So here is the official published text on the European Union publication office website (direct link to article 2)  https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32019L0790#art_2.tit_1 

Subsection 2 reads (which is the language that Laurent quoted): 

> ‘text and data mining’ means any automated analytical technique aimed at analysing text and data in digital form in order to generate information which includes but is not limited to patterns, trends and correlations;"

**Comment by lrosenthol** [comment]
Weird - I don't know where I got mine from.  Fixing!

**Comment by sposth** [comment]
Another variant: 
"Automated analysis of the work to extract information from it, especially about patterns, trends, and correlations for the purpose of ..."

**Comment by paul2keller** [comment]
@sposth I think we really want to align this with the CDSM definition. if we do not do that we would need to explain why we are using a different definition (so lets first resolve #6 and then see if there is any need for different language here)
