### ISSUE TITLE
Is all of search included in TDM?

### ISSUE THREAD

**Issue by paul2keller** [lrosenthol/opt-out-vocab#3]
Regarding search. I wonder if we are all on the same page here. Are we really all comfortable with saying that *all forms of search*, including those not specifically AI-enhanced, are a subset of TDM? Or is what we are aiming for here more like "AI-powered search and retrieval"? I assumed we were going for the latter, but the definition Leonard suggests ("The act of indexing the content (and/or metadata) of assets for the purpose of retrieval") seems to suggest the former.

**Comment by lrosenthol** [comment]
@paul2keller  I have always understood, since TDM itself "predates" AI, that it is all forms of Search (and Discovery).

**Comment by giuliamarangoni** [comment]
see my comment under issue 6

**Comment by paul2keller** [comment]
I have closed this issue, left #6 open for now as that has been where this question has been discussed more extensively
