### ISSUE TITLE
Do we need to account for override by Art 3 exception?

### ISSUE THREAD

**Issue by paul2keller** [lrosenthol/opt-out-vocab#5]
Do we need to account at the vocabulary level for the fact that the TDM opt-out (and thus all of the child use cases) are overridden (at least in the EU) by the Article 3 exception (at least for the beneficiaries of that exception). Or do we account for that somewhere else (ie leave this to the actual AI developers to figure out). My hunch is that we need to at least mention this least we give the wrong impression that these opt outs are absolute.

**Comment by lrosenthol** [comment]
If someone has some good text to add, I am happy to do so.

**Comment by paul2keller** [comment]
this is addressed in the definition of TDM in most recent version: 

> Text and Data Mining. The act of using one or more assets in the context of any automated analytical technique aimed at analysing text and data in digital form in order to generate information which includes but is not limited to patterns, trends and correlations for purposes **other than scientific research.**
